<h1>NUMPY</h1>

In [1]:
import numpy as np

<ol>
    <li><b>np.array(): </b> Create a new n dimension array</li>
    <li><b>np.arange(): </b> Similar to range() in python i.e, return sequence of elements</li>
    <li><b>np.ndim(): </b> Return the dimension of an array</li>
    <li><b>np.sum(): </b> Return the sum of all elements of array</li>
    <li><b>np.mean(): </b> Return mean of all elements of array</li>
    <li><b>np.dtype(): </b> Returns type of data in array</li>
    <li><b>np.concatenate(): </b> join two arrays</li>
    <li><b>np.shape(): </b> Returns number of elements in array</li>
    <li><b>np.std(): </b> Returns standard deviation number of elements in array</li>
    <li><b>np.var(): </b> Returns variance of number of elements in array</li>

</ol>

In [8]:
# Creating 1-D array using numpy
n1 = np.array([1,2,3,4])
print(n1)
print(n1.ndim)
print(n1.size)
print(n1.dtype)
print(type(n1))
print(n1.sum())

[1 2 3 4]
1
4
int32
<class 'numpy.ndarray'>
10


In [16]:
# Creating 2-D array
n2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n2)
print("Dimension:",n2.ndim)
print("Size of n2",n2.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension: 2
Size of n2 9


In [21]:
# Creating 3-D array
n3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(n3)
print("Dimension:",n3.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimension: 3


In [24]:
# Concatenate two numpy arrays
num1 = np.arange(5)
num2 = np.arange(5,11)
num3 = np.concatenate((num1,num2)) # while concatenation make su
print(num3)

[ 0  1  2  3  4  5  6  7  8  9 10]
